# Generated by extendr — do not edit by hand.
# Source: src/rust/src/lib.rs
#
# Calls into the compiled Rust library.  These wrappers are only active when
# the package was installed with native bindings (src/Makevars present and
# cargo available at install time).

#' @keywords internal
scx_convert <- function(input, output, chunk_size, dtype, assay, layer) {
  .Call(
    "wrap__scx_convert",
    input, output, chunk_size, dtype, assay, layer,
    PACKAGE = "picklerick"
  )
}
