# Generated by extendr — do not edit by hand.
# Source: src/rust/src/lib.rs
#
# Calls into the compiled Rust library.  These wrappers are only active when
# the package was installed with native bindings (src/Makevars present and
# cargo available at install time).

#' @keywords internal
scx_convert <- function(input, output, chunk_size, dtype, assay, layer) {
  .Call(
    "wrap__scx_convert",
    input, output, chunk_size, dtype, assay, layer,
    PACKAGE = "picklerick"
  )
}

#' @keywords internal
scx_inspect <- function(input, chunk_size) {
  .Call(
    "wrap__scx_inspect",
    input, chunk_size,
    PACKAGE = "picklerick"
  )
}

#' @keywords internal
scx_read <- function(input, chunk_size, read_x = TRUE) {
  .Call(
    "wrap__scx_read",
    input, chunk_size, read_x,
    PACKAGE = "picklerick"
  )
}

#' @keywords internal
scx_write_h5ad <- function(output, n_obs, n_vars,
                           x_indptr, x_indices, x_data,
                           obs_index, var_index,
                           obs_cols, var_cols,
                           uns_json, dtype) {
  .Call(
    "wrap__scx_write_h5ad",
    output, n_obs, n_vars,
    x_indptr, x_indices, x_data,
    obs_index, var_index,
    obs_cols, var_cols,
    uns_json, dtype,
    PACKAGE = "picklerick"
  )
}
