use futures::StreamExt;
use scx_core::bpcells::{
    bp128_unpack, decode_d1z, decode_for, zigzag_decode, zigzag_encode, BpcellsDatasetReader,
    BpcellsDirReader,
};
use scx_core::h5bpcells::{open_bpcells_h5, probe_bpcells_version};
use scx_core::stream::DatasetReader;
/// BPCells compatibility test suite.
///
/// Tests at three levels:
///   1. `inspect_*`   — probe the on-disk layout; require only std I/O
///   2. `codec_*`     — codec unit tests with hand-computed vectors (no I/O)
///   3. `roundtrip_*` — integration tests; read a fixture, verify against manifest
///
/// Fixtures are generated by `pixi run -e bpcells prepare-bpcells`.
use std::path::Path;

// ─── fixture paths ──────────────────────────────────────────────────────────

const FIXTURE_DIR: &str = "../../tests/golden/bpcells";
const MANIFEST: &str = "../../tests/golden/bpcells/manifest.json";

fn fixture(name: &str) -> std::path::PathBuf {
    Path::new(FIXTURE_DIR).join(name)
}

fn fixtures_present() -> bool {
    fixture("manifest.json").exists()
}

// ─── helpers ────────────────────────────────────────────────────────────────

fn read_bp_body(path: &Path) -> Vec<u8> {
    let data = std::fs::read(path).expect("read file");
    assert!(data.len() >= 8, "file too short: {:?}", path);
    data[8..].to_vec()
}

fn read_u32s(path: &Path) -> Vec<u32> {
    let body = read_bp_body(path);
    assert_eq!(body.len() % 4, 0);
    body.chunks_exact(4)
        .map(|c| u32::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn read_u64s(path: &Path) -> Vec<u64> {
    let body = read_bp_body(path);
    assert_eq!(body.len() % 8, 0);
    body.chunks_exact(8)
        .map(|c| u64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

// ─── 1. INSPECT TESTS ───────────────────────────────────────────────────────

/// Print every file in synth_packed_uint_csc: name, size, 8-byte header.
/// Run with: cargo test -p scx-core inspect_bpcells -- --nocapture
#[test]
fn inspect_bpcells_packed_uint() {
    let dir = fixture("synth_packed_uint_csc");
    if !dir.exists() {
        eprintln!("SKIP: fixture not found — run `pixi run -e bpcells prepare-bpcells`");
        return;
    }
    let mut entries: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .map(|e| e.unwrap())
        .collect();
    entries.sort_by_key(|e| e.file_name());
    for e in &entries {
        let path = e.path();
        let size = path.metadata().unwrap().len();
        let data = std::fs::read(&path).unwrap();
        let hdr = String::from_utf8_lossy(&data[..data.len().min(8)]);
        println!(
            "  {:<28} {:>8} bytes  header={:?}",
            e.file_name().to_str().unwrap(),
            size,
            hdr
        );
    }
}

/// Verify the packed-uint fixture matches the spec: correct files exist,
/// version string is right, binary headers are valid.
#[test]
fn inspect_bpcells_packed_uint_structural() {
    let dir = fixture("synth_packed_uint_csc");
    if !dir.exists() {
        eprintln!("SKIP");
        return;
    }

    // version string
    let version = std::fs::read_to_string(dir.join("version")).unwrap();
    assert_eq!(version.trim(), "packed-uint-matrix-v2", "version string");

    // storage_order
    let order = std::fs::read_to_string(dir.join("storage_order")).unwrap();
    assert_eq!(order.trim(), "col", "storage_order");

    // required files for packed-uint
    for name in &[
        "idxptr",
        "index_data",
        "index_idx",
        "index_idx_offsets",
        "index_starts",
        "val_data",
        "val_idx",
        "val_idx_offsets",
        "shape",
        "row_names",
        "col_names",
    ] {
        assert!(dir.join(name).exists(), "missing file: {name}");
    }

    // unpacked must NOT have *_data files
    let u_dir = fixture("synth_unpacked_uint_csc");
    assert!(u_dir.join("val").exists());
    assert!(u_dir.join("index").exists());
    assert!(
        !u_dir.join("val_data").exists(),
        "packed file in unpacked dir"
    );
    assert!(!u_dir.join("index_data").exists());

    // shape: UINT32v1 header + 2 u32 values → 16 bytes total
    let shape_bytes = std::fs::read(dir.join("shape")).unwrap();
    assert_eq!(&shape_bytes[..8], b"UINT32v1", "shape header");
    assert_eq!(shape_bytes.len(), 8 + 2 * 4, "shape size");

    // idxptr: UINT64v1 header + (n_cols+1) u64
    let idxptr_bytes = std::fs::read(dir.join("idxptr")).unwrap();
    assert_eq!(&idxptr_bytes[..8], b"UINT64v1", "idxptr header");
}

/// Verify unpacked fixture binary headers and array sizes.
#[test]
fn inspect_bpcells_unpacked_uint_values() {
    let dir = fixture("synth_unpacked_uint_csc");
    if !dir.exists() {
        eprintln!("SKIP");
        return;
    }

    let shape = read_u32s(&dir.join("shape"));
    let idxptr = read_u64s(&dir.join("idxptr"));
    let index = read_u32s(&dir.join("index"));
    let val = read_u32s(&dir.join("val"));

    assert_eq!(shape, vec![4, 5], "shape");
    assert_eq!(idxptr, vec![0, 2, 3, 5, 6, 8], "idxptr");
    assert_eq!(index, vec![0, 2, 1, 0, 3, 1, 2, 3], "index");
    assert_eq!(val, vec![1, 5, 2, 3, 7, 4, 6, 8], "val");

    // idxptr header
    let raw = std::fs::read(dir.join("idxptr")).unwrap();
    assert_eq!(&raw[..8], b"UINT64v1");

    // val header for unpacked uint is UINT32v1
    let raw_val = std::fs::read(dir.join("val")).unwrap();
    assert_eq!(&raw_val[..8], b"UINT32v1");
}

/// Verify packed arrays have the expected raw word values.
#[test]
fn inspect_bpcells_packed_uint_raw_words() {
    let dir = fixture("synth_packed_uint_csc");
    if !dir.exists() {
        eprintln!("SKIP");
        return;
    }

    let idxptr = read_u64s(&dir.join("idxptr"));
    let starts = read_u32s(&dir.join("index_starts"));
    let idx_idx = read_u32s(&dir.join("index_idx"));
    let idx_data = read_u32s(&dir.join("index_data"));
    let val_idx = read_u32s(&dir.join("val_idx"));
    let val_data = read_u32s(&dir.join("val_data"));

    assert_eq!(idxptr, vec![0, 2, 3, 5, 6, 8]);
    assert_eq!(starts, vec![0]);
    assert_eq!(idx_idx, vec![0, 12]);
    assert_eq!(val_idx, vec![0, 12]);
    assert_eq!(idx_data, vec![48, 28, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0]);
    assert_eq!(
        val_data,
        vec![
            4294967280, 4294967260, 4294967273, 4294967290, 4294967295, 4294967295, 4294967295,
            4294967295, 4294967295, 4294967295, 4294967295, 4294967295,
        ]
    );
}

/// Verify the 128-boundary fixture: exactly 128 nnz in column 0.
#[test]
fn inspect_bpcells_128_boundary() {
    let dir = fixture("synth_128_boundary");
    if !dir.exists() {
        eprintln!("SKIP");
        return;
    }

    let shape = read_u32s(&dir.join("shape"));
    let idxptr = read_u64s(&dir.join("idxptr"));
    let idx_idx = read_u32s(&dir.join("index_idx"));

    assert_eq!(shape, vec![128, 2]);
    assert_eq!(idxptr, vec![0, 128, 128]);
    assert_eq!(idx_idx, vec![0, 8]); // B=2 bits → 2*4=8 words for 128 values
}

/// Verify the empty fixture: 0 nnz, no panic.
#[test]
fn inspect_bpcells_empty() {
    let dir = fixture("synth_empty");
    if !dir.exists() {
        eprintln!("SKIP");
        return;
    }

    let shape = read_u32s(&dir.join("shape"));
    let idxptr = read_u64s(&dir.join("idxptr"));
    let idx_idx = read_u32s(&dir.join("index_idx"));

    assert_eq!(shape, vec![4, 5]);
    assert_eq!(idxptr, vec![0, 0, 0, 0, 0, 0]); // 5 cols, all empty
    assert_eq!(idx_idx, vec![0]); // no chunks
}

// ─── 2. CODEC UNIT TESTS ────────────────────────────────────────────────────
// No filesystem I/O — all expected values hand-computed or derived from the
// BPCells C++ reference implementation (test-bp128.cpp) + Python decoder.

/// BP-128 raw unpack: B=0 → all zeros.
#[test]
fn codec_bp128_b0_is_zero() {
    let out = bp128_unpack(0, &[]);
    assert_eq!(out, [0u32; 128]);
}

/// BP-128-D1Z decode: the synth 4×5 fixture index array.
///
/// Packed data (12 words, B=3): `index_data = [48, 28, 17, 17, 0×8]`
/// `index_starts[0] = 0`
/// Expected (first 8 values): `[0, 2, 1, 0, 3, 1, 2, 3]`
#[test]
fn codec_d1z_decode_synth_index() {
    let packed: [u32; 12] = [48, 28, 17, 17, 0, 0, 0, 0, 0, 0, 0, 0];
    let chunk_offsets = [0u32, 12];
    let starts = [0u32];

    let decoded = decode_d1z(&packed, &chunk_offsets, &starts, 8);
    assert_eq!(decoded, vec![0u32, 2, 1, 0, 3, 1, 2, 3]);
}

/// BP-128-FOR decode: the synth 4×5 fixture val array.
///
/// Packed data (12 words, B=3): `val_data = [0xFFFFFFF0, 0xFFFFFFDC, ...]`
/// Expected (first 8 values): `[1, 5, 2, 3, 7, 4, 6, 8]`
#[test]
fn codec_for_decode_synth_val() {
    let packed: [u32; 12] = [
        4294967280, 4294967260, 4294967273, 4294967290, 4294967295, 4294967295, 4294967295,
        4294967295, 4294967295, 4294967295, 4294967295, 4294967295,
    ];
    let chunk_offsets = [0u32, 12];

    let decoded = decode_for(&packed, &chunk_offsets, 8);
    assert_eq!(decoded, vec![1u32, 5, 2, 3, 7, 4, 6, 8]);
}

/// BP-128-D1Z: 128-boundary — exactly one full chunk, sorted indices 0..127.
///
/// zigzag-encoded deltas: `[0, 2, 2, ..., 2]` (one zero then 127 twos).
/// B = 2 bits. Expected word pattern: lane 0 word 0 = 0xAAAAAAAA (alternating bits for val=2),
/// but lane 0 position 0 = 0, so word 0 = 0b10101010...0 = 0xAAAAAAAA - the lane-0 bit pattern
/// for [0, 2, 2, ...] is still 0xAAAAAAAA since position 0 in lane 0 is 0 (bit pattern 00)
/// and subsequent lane-0 positions are 2 (bit pattern 10).
/// Confirmed by Python reference decoder.
#[test]
fn codec_d1z_decode_128_boundary() {
    let packed: [u32; 8] = [
        2863311528, 2863311530, 2863311530, 2863311530, 2863311530, 2863311530, 2863311530,
        2863311530,
    ];
    let chunk_offsets = [0u32, 8];
    let starts = [0u32];
    let expected: Vec<u32> = (0..128).collect();

    let decoded = decode_d1z(&packed, &chunk_offsets, &starts, 128);
    assert_eq!(decoded, expected);
}

/// Zigzag encoding round-trip for a mix of positive and negative values.
#[test]
fn codec_zigzag_round_trip() {
    let cases: &[(i32, u32)] = &[
        (0, 0),
        (1, 2),
        (-1, 1),
        (2, 4),
        (-2, 3),
        (i32::MAX, u32::MAX - 1),
        (i32::MIN, u32::MAX),
    ];
    for &(raw, expected) in cases {
        let enc = zigzag_encode(raw);
        assert_eq!(enc, expected, "zigzag_encode({raw})");
        let dec = zigzag_decode(expected);
        assert_eq!(dec, raw, "zigzag_decode({expected})");
    }
}

// ─── 2b. PARALLEL CODEC TESTS ───────────────────────────────────────────────
// Verify that the Rayon parallel decode paths produce identical results to the
// hand-computed expected output, regardless of thread count.
//
// Both tests use a b=0 synthetic stream (zero packed words per chunk) to keep
// fixture generation trivial while exercising the full parallel dispatch.
// N_CHUNKS = 266 > 256 (RAYON_CHUNK_THRESHOLD) → always hits the parallel path.

/// Parallel decode_for produces correct results across thread counts.
///
/// b=0 stream: every chunk decodes to 128 ones (packed value 0 → v = 0+1 = 1).
#[test]
fn parallel_for_matches_sequential() {
    const N_CHUNKS: usize = 266;
    const COUNT: usize = N_CHUNKS * 128;

    let data: Vec<u32> = vec![];
    let offsets: Vec<u32> = vec![0u32; N_CHUNKS + 1];
    let expected = vec![1u32; COUNT];

    for n_threads in [1, 2, 4, rayon::current_num_threads()] {
        let result = rayon::ThreadPoolBuilder::new()
            .num_threads(n_threads)
            .build()
            .unwrap()
            .install(|| decode_for(&data, &offsets, COUNT));
        assert_eq!(
            result, expected,
            "decode_for wrong with {n_threads} thread(s)"
        );
    }
}

/// Parallel decode_d1z produces correct results across thread counts.
///
/// b=0 stream with starts[k]=k: all deltas are zero, so chunk k outputs 128
/// copies of k. Easy to verify without encoding anything.
#[test]
fn parallel_d1z_matches_sequential() {
    const N_CHUNKS: usize = 266;
    const COUNT: usize = N_CHUNKS * 128;

    let data: Vec<u32> = vec![];
    let offsets: Vec<u32> = vec![0u32; N_CHUNKS + 1];
    let starts: Vec<u32> = (0..N_CHUNKS as u32).collect();

    // chunk k → 128 copies of k
    let expected: Vec<u32> = (0..N_CHUNKS as u32)
        .flat_map(|k| std::iter::repeat(k).take(128))
        .collect();

    for n_threads in [1, 2, 4, rayon::current_num_threads()] {
        let result = rayon::ThreadPoolBuilder::new()
            .num_threads(n_threads)
            .build()
            .unwrap()
            .install(|| decode_d1z(&data, &offsets, &starts, COUNT));
        assert_eq!(
            result, expected,
            "decode_d1z wrong with {n_threads} thread(s)"
        );
    }
}

// ─── 3. INTEGRATION TESTS ───────────────────────────────────────────────────

fn load_manifest() -> serde_json::Value {
    let s = std::fs::read_to_string(MANIFEST).expect("read manifest.json");
    serde_json::from_str(&s).unwrap()
}

/// Read the manifest expected dense matrix for a fixture.
/// Returns `(nrow, ncol, flat_row_major_values)`.
fn expected_dense(manifest: &serde_json::Value, name: &str) -> (usize, usize, Vec<f64>) {
    let m = &manifest[name];
    let nrow = m["nrow"].as_u64().unwrap() as usize;
    let ncol = m["ncol"].as_u64().unwrap() as usize;
    let vals: Vec<f64> = m["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    (nrow, ncol, vals)
}

#[test]
fn roundtrip_synth_packed_uint_csc() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_packed_uint_csc");

    let r = BpcellsDirReader::open(&fixture("synth_packed_uint_csc")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_packed_uint_csc");
}

#[test]
fn roundtrip_synth_unpacked_uint_csc() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_unpacked_uint_csc");

    let r = BpcellsDirReader::open(&fixture("synth_unpacked_uint_csc")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_unpacked_uint_csc");
}

/// Packed and unpacked paths must reconstruct the same dense matrix.
#[test]
fn roundtrip_packed_unpacked_agree() {
    if !fixtures_present() {
        return;
    }
    let packed = BpcellsDirReader::open(&fixture("synth_packed_uint_csc")).unwrap();
    let unpacked = BpcellsDirReader::open(&fixture("synth_unpacked_uint_csc")).unwrap();
    assert_eq!(packed.to_dense_f64(), unpacked.to_dense_f64());
}

#[test]
fn roundtrip_synth_packed_float_csc() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_packed_float_csc");

    let r = BpcellsDirReader::open(&fixture("synth_packed_float_csc")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    // float32 has limited precision; compare with tolerance
    let dense = r.to_dense_f64();
    assert_eq!(dense.len(), expected.len());
    for (a, b) in dense.iter().zip(expected.iter()) {
        assert!(
            (a - b).abs() < 1e-5,
            "float mismatch: got {a}, expected {b}"
        );
    }
}

#[test]
fn roundtrip_synth_packed_double_csc() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_packed_double_csc");

    let r = BpcellsDirReader::open(&fixture("synth_packed_double_csc")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_packed_double_csc");
}

#[test]
fn roundtrip_synth_packed_uint_csr() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_packed_uint_csr");

    let r = BpcellsDirReader::open(&fixture("synth_packed_uint_csr")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_packed_uint_csr");
}

#[test]
fn roundtrip_synth_empty() {
    if !fixtures_present() {
        return;
    }
    let r = BpcellsDirReader::open(&fixture("synth_empty")).unwrap();
    assert_eq!(r.nrow, 4);
    assert_eq!(r.ncol, 5);
    let dense = r.to_dense_f64();
    assert_eq!(dense, vec![0.0f64; 4 * 5]);
}

#[test]
fn roundtrip_synth_one_col() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_one_col");

    let r = BpcellsDirReader::open(&fixture("synth_one_col")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_one_col");
}

#[test]
fn roundtrip_synth_large_vals() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_large_vals");

    let r = BpcellsDirReader::open(&fixture("synth_large_vals")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_large_vals");
}

#[test]
fn roundtrip_synth_128_boundary() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_128_boundary");

    let r = BpcellsDirReader::open(&fixture("synth_128_boundary")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_128_boundary");
}

#[test]
fn roundtrip_synth_256_boundary() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    let (nrow, ncol, expected) = expected_dense(&mf, "synth_256_boundary");

    let r = BpcellsDirReader::open(&fixture("synth_256_boundary")).unwrap();
    assert_eq!(r.nrow, nrow);
    assert_eq!(r.ncol, ncol);
    let dense = r.to_dense_f64();
    assert_eq!(dense, expected, "synth_256_boundary");
}

#[test]
fn roundtrip_synth_large_vals_exact() {
    if !fixtures_present() {
        return;
    }
    // Verify exact integer round-trip for values up to 2^31-1.
    let r = BpcellsDirReader::open(&fixture("synth_large_vals")).unwrap();
    let dense = r.to_dense_u32();
    // Diagonal: [2147483647, 1073741824, 1, 1000000]
    assert_eq!(dense[0 * 4 + 0], 2147483647u32, "2^31-1");
    assert_eq!(dense[1 * 4 + 1], 1073741824u32, "2^30");
    assert_eq!(dense[2 * 4 + 2], 1u32);
    assert_eq!(dense[3 * 4 + 3], 1000000u32);
    // Off-diagonal must be 0
    assert_eq!(dense[0 * 4 + 1], 0);
    assert_eq!(dense[1 * 4 + 0], 0);
}

// ─── 4. DATASET READER TESTS ────────────────────────────────────────────────
// BpcellsDatasetReader implements the DatasetReader trait.

/// Helper: consume x_stream and reconstruct a dense row-major matrix.
async fn stream_to_dense(reader: &mut BpcellsDatasetReader) -> Vec<f64> {
    let (n_obs, n_vars) = reader.shape();
    let mut dense = vec![0.0f64; n_obs * n_vars];
    let mut stream = reader.x_stream();
    while let Some(chunk) = stream.next().await {
        let chunk = chunk.unwrap();
        let csr = &chunk.data;
        for row in 0..chunk.nrows {
            let obs = chunk.row_offset + row;
            let start = csr.indptr[row] as usize;
            let end = csr.indptr[row + 1] as usize;
            for k in start..end {
                let var = csr.indices[k] as usize;
                let v = match &csr.data {
                    scx_core::dtype::TypedVec::U32(vs) => vs[k] as f64,
                    scx_core::dtype::TypedVec::F32(vs) => vs[k] as f64,
                    scx_core::dtype::TypedVec::F64(vs) => vs[k],
                    scx_core::dtype::TypedVec::I32(vs) => vs[k] as f64,
                };
                dense[obs * n_vars + var] = v;
            }
        }
    }
    dense
}

/// Basic shape + obs/var names for a CSC matrix.
///
/// For CSC (genes×cells): n_obs = ncol = 5 cells, n_vars = nrow = 4 genes.
#[tokio::test]
async fn dataset_reader_shape_and_names() {
    if !fixtures_present() {
        return;
    }
    let r = BpcellsDatasetReader::open(&fixture("synth_packed_uint_csc"), 1000).unwrap();
    assert_eq!(r.shape(), (5, 4), "(n_obs=cells, n_vars=genes)");
    assert_eq!(r.n_obs, 5);
    assert_eq!(r.n_vars, 4);
}

/// Stream all cells in one chunk; verify dense reconstruction matches manifest.
#[tokio::test]
async fn dataset_reader_stream_full() {
    if !fixtures_present() {
        return;
    }
    let mf = load_manifest();
    // manifest stores the logical matrix as [n_genes=4 rows × n_cells=5 cols] (R convention).
    // DatasetReader returns [n_obs=5 rows × n_vars=4 cols] (AnnData convention).
    // These are transposes of each other, so we compare the transposed manifest.
    let (n_genes, n_cells, manifest_vals) = expected_dense(&mf, "synth_packed_uint_csc");
    // manifest is row-major [genes × cells]: manifest_vals[gene * n_cells + cell]
    // DatasetReader output is row-major [cells × genes]: dense[cell * n_genes + gene]
    let expected: Vec<f64> = (0..n_cells)
        .flat_map(|cell| {
            let mv = &manifest_vals;
            (0..n_genes)
                .map(move |gene| mv[gene * n_cells + cell])
                .collect::<Vec<_>>()
        })
        .collect();

    let mut r = BpcellsDatasetReader::open(&fixture("synth_packed_uint_csc"), 1000).unwrap();
    let dense = stream_to_dense(&mut r).await;
    assert_eq!(dense, expected);
}

/// Chunked streaming: chunk_size = 2, verify nnz totals and chunk boundaries.
#[tokio::test]
async fn dataset_reader_stream_chunked() {
    if !fixtures_present() {
        return;
    }
    let mut r = BpcellsDatasetReader::open(&fixture("synth_packed_uint_csc"), 2).unwrap();
    let (n_obs, _) = r.shape();

    let mut total_nnz = 0usize;
    let mut total_rows = 0usize;
    let mut prev_end = 0usize;

    let mut stream = r.x_stream();
    while let Some(chunk) = stream.next().await {
        let chunk = chunk.unwrap();
        assert_eq!(chunk.row_offset, prev_end, "row_offset must be contiguous");
        assert!(chunk.nrows <= 2, "chunk exceeds chunk_size");
        total_rows += chunk.nrows;
        total_nnz += chunk.data.indices.len();
        prev_end += chunk.nrows;
    }
    assert_eq!(total_rows, n_obs);
    assert_eq!(total_nnz, 8, "8 nnz in synth 4×5 matrix");
}

/// CSR-stored matrix streams correctly (n_obs = nrow, n_vars = ncol).
#[tokio::test]
async fn dataset_reader_csr_shape() {
    if !fixtures_present() {
        return;
    }
    // synth_packed_uint_csr: shape [4,5] with storage_order=row.
    // For CSR: n_obs = nrow = 4, n_vars = ncol = 5.
    let r = BpcellsDatasetReader::open(&fixture("synth_packed_uint_csr"), 1000).unwrap();
    assert_eq!(r.shape(), (4, 5), "CSR: n_obs=nrow=4, n_vars=ncol=5");
}

/// Empty matrix: zero nnz, stream yields zero chunks with correct shape.
#[tokio::test]
async fn dataset_reader_empty() {
    if !fixtures_present() {
        return;
    }
    // synth_empty: shape [4,5] CSC → n_obs=5, n_vars=4
    let mut r = BpcellsDatasetReader::open(&fixture("synth_empty"), 100).unwrap();
    assert_eq!(r.shape(), (5, 4));

    let mut total_nnz = 0usize;
    let mut stream = r.x_stream();
    while let Some(chunk) = stream.next().await {
        total_nnz += chunk.unwrap().data.indices.len();
    }
    assert_eq!(total_nnz, 0);
}

/// 256-boundary: two full BP-128 chunks; stream accumulates correct nnz.
#[tokio::test]
async fn dataset_reader_256_boundary_nnz() {
    if !fixtures_present() {
        return;
    }
    // synth_256_boundary: 256 nnz all in col 0; CSC → n_obs=2, n_vars=256
    let mut r = BpcellsDatasetReader::open(&fixture("synth_256_boundary"), 1).unwrap();
    assert_eq!(r.shape(), (2, 256));

    let mut total_nnz = 0usize;
    let mut stream = r.x_stream();
    while let Some(chunk) = stream.next().await {
        total_nnz += chunk.unwrap().data.indices.len();
    }
    assert_eq!(total_nnz, 256);
}

// ─── HDF5 BPCells probe ──────────────────────────────────────────────────────

const H5_BPCELLS_FIXTURE: &str = "../../tests/golden/seurat_v5_bpcells.h5seurat";

/// Probe an H5Seurat file for BPCells-backed assays.
///
/// Skips silently when the fixture is absent; run with `-- --nocapture` to see
/// output.  Place a Seurat v5 .h5seurat file at `tests/golden/seurat_v5_bpcells.h5seurat`
/// (generated e.g. via `SaveH5Seurat` after `as.BPCells`) to exercise this path.
#[test]
fn inspect_bpcells_h5seurat() {
    let path = Path::new(H5_BPCELLS_FIXTURE);
    if !path.exists() {
        println!("SKIP inspect_bpcells_h5seurat: fixture not found at {H5_BPCELLS_FIXTURE}");
        return;
    }

    let file = hdf5::File::open(path).expect("open h5seurat");

    // Collect candidate group paths to probe.  Seurat v5 typically writes
    // BPCells matrices under "assays/{assay}/layers/{layer}" or
    // "assays/{assay}/{layer}".
    let mut candidates: Vec<String> = Vec::new();
    if let Ok(assays_grp) = file.group("assays") {
        for assay in assays_grp.member_names().unwrap_or_default() {
            // v5 path: assays/{assay}/layers/{layer}
            let layers_path = format!("assays/{assay}/layers");
            if let Ok(layers_grp) = file.group(&layers_path) {
                for layer in layers_grp.member_names().unwrap_or_default() {
                    candidates.push(format!("assays/{assay}/layers/{layer}"));
                }
            }
            // v3/v4 path: assays/{assay}/{layer}
            if let Ok(assay_grp) = file.group(&format!("assays/{assay}")) {
                for member in assay_grp.member_names().unwrap_or_default() {
                    let p = format!("assays/{assay}/{member}");
                    candidates.push(p);
                }
            }
        }
    }

    println!("Probing {} candidate group(s):", candidates.len());
    let mut found_any = false;
    for path_str in &candidates {
        match probe_bpcells_version(&file, path_str) {
            Some(version) => {
                println!("  [BPCells v={version}] {path_str}");
                match open_bpcells_h5(&file, path_str, 1000) {
                    Ok(reader) => {
                        let (n_obs, n_vars) = reader.shape();
                        println!("    shape: n_obs={n_obs}, n_vars={n_vars}");
                    }
                    Err(e) => println!("    open_bpcells_h5 error: {e}"),
                }
                found_any = true;
            }
            None => println!("  [dgCMatrix / other] {path_str}"),
        }
    }

    if !found_any {
        println!("No BPCells groups detected in {H5_BPCELLS_FIXTURE}");
    }
}
